name: TeleportScrolls
version: 1.0.0
author: Snipey
website: snipey.dev
main: dev.snipey.teleportscrolls.TeleportScrolls
api-version: 1.15

commands:
  scroll:
    description: Main interaction with the scroll cmd
    usage: /scroll <task>